- job:
    name: ansible-role-nodepool-base
    pre-run: tests/playbooks/pre.yaml
    run: tests/playbooks/run.yaml
    post-run:
      - tests/playbooks/post.yaml
      - tests/collect-logs.yaml
    roles:
      - zuul: openstack/ansible-role-nodepool
      - zuul: openstack/zuul-jobs

# Testing for nodepool_install_method: pip
- job:
    name: ansible-role-nodepool
    parent: ansible-role-nodepool-base

- job:
    name: ansible-role-nodepool-fedora-latest
    parent: ansible-role-nodepool
    nodeset: fedora-latest

- job:
    name: ansible-role-nodepool-ubuntu-bionic
    parent: ansible-role-nodepool
    nodeset: ubuntu-bionic

- job:
    name: ansible-role-nodepool-ubuntu-xenial
    parent: ansible-role-nodepool
    nodeset: ubuntu-xenial

# Testing for nodepool_install_method: git
- job:
    name: ansible-role-nodepool-src
    parent: ansible-role-nodepool-base
    required-projects:
      - name: openstack-infra/nodepool
    vars:
      nodepool_git_update: false
      nodepool_install_method: git

- job:
    name: ansible-role-nodepool-src-fedora-latest
    parent: ansible-role-nodepool-src
    nodeset: fedora-latest

- job:
    name: ansible-role-nodepool-src-ubuntu-bionic
    parent: ansible-role-nodepool-src
    nodeset: ubuntu-bionic

- job:
    name: ansible-role-nodepool-src-ubuntu-xenial
    parent: ansible-role-nodepool-src
    nodeset: ubuntu-xenial

- job:
    name: ansible-role-nodepool-docker
    parent: ansible-role-nodepool-base
    vars:
      nodepool_install_method: docker

# Testing for nodepool_install_method: docker
- job:
    name: ansible-role-nodepool-docker-ubuntu-bionic
    parent: ansible-role-nodepool-docker
    nodeset: ubuntu-bionic

- project:
    name: openstack/ansible-role-nodepool
    templates:
      - windmill-jobs-fedora-latest
      - windmill-jobs-bionic
      - windmill-jobs-xenial
    check:
      jobs:
        - ansible-role-nodepool-docker-ubuntu-xenial
        - ansible-role-nodepool-fedora-latest
        - ansible-role-nodepool-ubuntu-bionic
        - ansible-role-nodepool-ubuntu-xenial
        - ansible-role-nodepool-src-fedora-latest
        - ansible-role-nodepool-src-ubuntu-bionic
        - ansible-role-nodepool-src-ubuntu-xenial
        - tox-linters
    gate:
      jobs:
        - ansible-role-nodepool-fedora-latest
        - ansible-role-nodepool-ubuntu-bionic
        - ansible-role-nodepool-ubuntu-xenial
        - ansible-role-nodepool-src-fedora-latest
        - ansible-role-nodepool-src-ubuntu-bionic
        - ansible-role-nodepool-src-ubuntu-xenial
        - tox-linters
