---
- job:
    name: ansible-role-nodepool-base
    pre-run: tests/playbooks/pre.yaml
    run: tests/playbooks/run.yaml
    post-run:
      - tests/playbooks/post.yaml
      - tests/collect-logs.yaml
    roles:
      - zuul: openstack/ansible-role-nodepool

# Testing for nodepool_install_method: pip
- job:
    name: ansible-role-nodepool
    parent: ansible-role-nodepool-base

- job:
    name: ansible-role-nodepool-fedora-latest
    parent: ansible-role-nodepool
    nodeset: fedora-latest

- job:
    name: ansible-role-nodepool-ubuntu-bionic
    parent: ansible-role-nodepool
    nodeset: ubuntu-bionic

# Testing for nodepool_install_method: git
- job:
    name: ansible-role-nodepool-src
    parent: ansible-role-nodepool-base
    required-projects:
      - name: openstack-infra/nodepool
    vars:
      nodepool_git_update: false
      nodepool_install_method: git

- job:
    name: ansible-role-nodepool-src-fedora-latest
    parent: ansible-role-nodepool-src
    nodeset: fedora-latest

- job:
    name: ansible-role-nodepool-src-ubuntu-bionic
    parent: ansible-role-nodepool-src
    nodeset: ubuntu-bionic

# Testing for nodepool_install_method: docker
- job:
    name: ansible-role-nodepool-docker
    parent: ansible-role-nodepool-base
    nodeset: ubuntu-bionic
    vars:
      nodepool_install_method: docker
      nodepool_file_nodepool_builder_service_src: etc/systemd/system/nodepool-builder.service.j2
      nodepool_file_nodepool_launcher_service_src: etc/systemd/system/nodepool-launcher.service.j2

- project:
    templates:
      - windmill-jobs-fedora-latest
      - windmill-jobs-bionic
    check:
      jobs:
        - ansible-role-nodepool-docker
        - ansible-role-nodepool-fedora-latest
        - ansible-role-nodepool-ubuntu-bionic
        - ansible-role-nodepool-src-fedora-latest
        - ansible-role-nodepool-src-ubuntu-bionic
        - tox-linters
        - windmill-tox-molecule
    gate:
      jobs:
        - ansible-role-nodepool-docker
        - ansible-role-nodepool-fedora-latest
        - ansible-role-nodepool-ubuntu-bionic
        - ansible-role-nodepool-src-fedora-latest
        - ansible-role-nodepool-src-ubuntu-bionic
        - tox-linters
        - windmill-tox-molecule
