- job:
    name: ansible-role-nodepool-ubuntu-xenial
    run: tests/test001
    roles:
      - zuul: openstack/ansible-role-nodepool

- project:
    name: openstack/ansible-role-nodepool
    check:
      jobs:
        - ansible-role-nodepool-ubuntu-xenial
