- job:
    name: ansible-role-nodepool
    run: tests/test.yaml
    post-run: tests/collect-logs.yaml
    required-projects:
      - name: openstack-infra/nodepool
    roles:
      - zuul: openstack/ansible-role-nodepool

- job:
    name: ansible-role-nodepool-fedora-27
    parent: ansible-role-nodepool
    nodeset: fedora-27

- job:
    name: ansible-role-nodepool-ubuntu-bionic
    parent: ansible-role-nodepool
    nodeset: ubuntu-bionic

- job:
    name: ansible-role-nodepool-ubuntu-xenial
    parent: ansible-role-nodepool
    nodeset: ubuntu-xenial

- project:
    name: openstack/ansible-role-nodepool
    templates:
      - windmill-jobs-fedora-27
      - windmill-jobs-xenial
    check:
      jobs:
        - ansible-role-nodepool-fedora-27
        - ansible-role-nodepool-ubuntu-bionic
        - ansible-role-nodepool-ubuntu-xenial
        - tox-linters
    gate:
      jobs:
        - ansible-role-nodepool-fedora-27
        - ansible-role-nodepool-ubuntu-xenial
        - tox-linters
