---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ubuntu-bionic
    image: ubuntu:bionic
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        nodepool_service_nodepool_builder_manage: false
        nodepool_service_nodepool_launcher_manage: false
  playbooks:
    converge: ../../tests/playbooks/run.yaml
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
