---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ubuntu-bionic
    image: ubuntu:bionic
provisioner:
  name: ansible
  config_options:
    ssh_connection:
      pipelining: true
  inventory:
    group_vars:
      all:
        nodepool_service_nodepool_builder_manage: false
        nodepool_service_nodepool_launcher_manage: false
  lint:
    name: ansible-lint
  log: true
  playbooks:
    converge: ../../tests/playbooks/run.yaml
scenario:
  name: default
verifier:
  name: testinfra
  directory: ../tests
  options:
    verbose: true
  lint:
    name: flake8
