---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: False
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: localhost
provisioner:
  name: ansible
  playbooks:
    converge: ../../tests/playbooks/run.yaml
scenario:
  name: zuul
verifier:
  name: testinfra
  options:
    sudo: true
    verbose: true
  directory: ../default/tests
